services:
  - type: web
    name: atulride
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CASHFREE_ENV
        value: sandbox
      - key: CASHFREE_CLIENT_ID
        sync: false
      - key: CASHFREE_CLIENT_SECRET
        sync: false
      - key: PUBLIC_URL
        sync: false
